// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
)

// AuthUserUserPermission is an object representing the database table.
type AuthUserUserPermission struct {
	ID           int `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID       int `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PermissionID int `boil:"permission_id" json:"permission_id" toml:"permission_id" yaml:"permission_id"`

	R *authUserUserPermissionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L authUserUserPermissionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// authUserUserPermissionR is where relationships are stored.
type authUserUserPermissionR struct {
	Permission *AuthPermission
	User       *AuthUser
}

// authUserUserPermissionL is where Load methods for each relationship are stored.
type authUserUserPermissionL struct{}

var (
	authUserUserPermissionColumns               = []string{"id", "user_id", "permission_id"}
	authUserUserPermissionColumnsWithoutDefault = []string{"user_id", "permission_id"}
	authUserUserPermissionColumnsWithDefault    = []string{"id"}
	authUserUserPermissionPrimaryKeyColumns     = []string{"id"}
)

type (
	// AuthUserUserPermissionSlice is an alias for a slice of pointers to AuthUserUserPermission.
	// This should generally be used opposed to []AuthUserUserPermission.
	AuthUserUserPermissionSlice []*AuthUserUserPermission

	authUserUserPermissionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	authUserUserPermissionType                 = reflect.TypeOf(&AuthUserUserPermission{})
	authUserUserPermissionMapping              = queries.MakeStructMapping(authUserUserPermissionType)
	authUserUserPermissionPrimaryKeyMapping, _ = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, authUserUserPermissionPrimaryKeyColumns)
	authUserUserPermissionInsertCacheMut       sync.RWMutex
	authUserUserPermissionInsertCache          = make(map[string]insertCache)
	authUserUserPermissionUpdateCacheMut       sync.RWMutex
	authUserUserPermissionUpdateCache          = make(map[string]updateCache)
	authUserUserPermissionUpsertCacheMut       sync.RWMutex
	authUserUserPermissionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single authUserUserPermission record from the query, and panics on error.
func (q authUserUserPermissionQuery) OneP() *AuthUserUserPermission {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single authUserUserPermission record from the query.
func (q authUserUserPermissionQuery) One() (*AuthUserUserPermission, error) {
	o := &AuthUserUserPermission{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for auth_user_user_permissions")
	}

	return o, nil
}

// AllP returns all AuthUserUserPermission records from the query, and panics on error.
func (q authUserUserPermissionQuery) AllP() AuthUserUserPermissionSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all AuthUserUserPermission records from the query.
func (q authUserUserPermissionQuery) All() (AuthUserUserPermissionSlice, error) {
	var o AuthUserUserPermissionSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AuthUserUserPermission slice")
	}

	return o, nil
}

// CountP returns the count of all AuthUserUserPermission records in the query, and panics on error.
func (q authUserUserPermissionQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all AuthUserUserPermission records in the query.
func (q authUserUserPermissionQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count auth_user_user_permissions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q authUserUserPermissionQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q authUserUserPermissionQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if auth_user_user_permissions exists")
	}

	return count > 0, nil
}

// PermissionG pointed to by the foreign key.
func (o *AuthUserUserPermission) PermissionG(mods ...qm.QueryMod) authPermissionQuery {
	return o.Permission(boil.GetDB(), mods...)
}

// Permission pointed to by the foreign key.
func (o *AuthUserUserPermission) Permission(exec boil.Executor, mods ...qm.QueryMod) authPermissionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.PermissionID),
	}

	queryMods = append(queryMods, mods...)

	query := AuthPermissions(exec, queryMods...)
	queries.SetFrom(query.Query, "`auth_permission`")

	return query
}

// UserG pointed to by the foreign key.
func (o *AuthUserUserPermission) UserG(mods ...qm.QueryMod) authUserQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *AuthUserUserPermission) User(exec boil.Executor, mods ...qm.QueryMod) authUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := AuthUsers(exec, queryMods...)
	queries.SetFrom(query.Query, "`auth_user`")

	return query
}

// LoadPermission allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (authUserUserPermissionL) LoadPermission(e boil.Executor, singular bool, maybeAuthUserUserPermission interface{}) error {
	var slice []*AuthUserUserPermission
	var object *AuthUserUserPermission

	count := 1
	if singular {
		object = maybeAuthUserUserPermission.(*AuthUserUserPermission)
	} else {
		slice = *maybeAuthUserUserPermission.(*AuthUserUserPermissionSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &authUserUserPermissionR{}
		}
		args[0] = object.PermissionID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &authUserUserPermissionR{}
			}
			args[i] = obj.PermissionID
		}
	}

	query := fmt.Sprintf(
		"select * from `auth_permission` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AuthPermission")
	}
	defer results.Close()

	var resultSlice []*AuthPermission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AuthPermission")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Permission = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PermissionID == foreign.ID {
				local.R.Permission = foreign
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (authUserUserPermissionL) LoadUser(e boil.Executor, singular bool, maybeAuthUserUserPermission interface{}) error {
	var slice []*AuthUserUserPermission
	var object *AuthUserUserPermission

	count := 1
	if singular {
		object = maybeAuthUserUserPermission.(*AuthUserUserPermission)
	} else {
		slice = *maybeAuthUserUserPermission.(*AuthUserUserPermissionSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &authUserUserPermissionR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &authUserUserPermissionR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from `auth_user` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AuthUser")
	}
	defer results.Close()

	var resultSlice []*AuthUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AuthUser")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// SetPermissionG of the auth_user_user_permission to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.PermissionAuthUserUserPermissions.
// Uses the global database handle.
func (o *AuthUserUserPermission) SetPermissionG(insert bool, related *AuthPermission) error {
	return o.SetPermission(boil.GetDB(), insert, related)
}

// SetPermissionP of the auth_user_user_permission to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.PermissionAuthUserUserPermissions.
// Panics on error.
func (o *AuthUserUserPermission) SetPermissionP(exec boil.Executor, insert bool, related *AuthPermission) {
	if err := o.SetPermission(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPermissionGP of the auth_user_user_permission to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.PermissionAuthUserUserPermissions.
// Uses the global database handle and panics on error.
func (o *AuthUserUserPermission) SetPermissionGP(insert bool, related *AuthPermission) {
	if err := o.SetPermission(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetPermission of the auth_user_user_permission to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.PermissionAuthUserUserPermissions.
func (o *AuthUserUserPermission) SetPermission(exec boil.Executor, insert bool, related *AuthPermission) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `auth_user_user_permissions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"permission_id"}),
		strmangle.WhereClause("`", "`", 0, authUserUserPermissionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PermissionID = related.ID

	if o.R == nil {
		o.R = &authUserUserPermissionR{
			Permission: related,
		}
	} else {
		o.R.Permission = related
	}

	if related.R == nil {
		related.R = &authPermissionR{
			PermissionAuthUserUserPermissions: AuthUserUserPermissionSlice{o},
		}
	} else {
		related.R.PermissionAuthUserUserPermissions = append(related.R.PermissionAuthUserUserPermissions, o)
	}

	return nil
}

// SetUserG of the auth_user_user_permission to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAuthUserUserPermissions.
// Uses the global database handle.
func (o *AuthUserUserPermission) SetUserG(insert bool, related *AuthUser) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the auth_user_user_permission to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAuthUserUserPermissions.
// Panics on error.
func (o *AuthUserUserPermission) SetUserP(exec boil.Executor, insert bool, related *AuthUser) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the auth_user_user_permission to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAuthUserUserPermissions.
// Uses the global database handle and panics on error.
func (o *AuthUserUserPermission) SetUserGP(insert bool, related *AuthUser) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the auth_user_user_permission to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserAuthUserUserPermissions.
func (o *AuthUserUserPermission) SetUser(exec boil.Executor, insert bool, related *AuthUser) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `auth_user_user_permissions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, authUserUserPermissionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID

	if o.R == nil {
		o.R = &authUserUserPermissionR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &authUserR{
			UserAuthUserUserPermissions: AuthUserUserPermissionSlice{o},
		}
	} else {
		related.R.UserAuthUserUserPermissions = append(related.R.UserAuthUserUserPermissions, o)
	}

	return nil
}

// AuthUserUserPermissionsG retrieves all records.
func AuthUserUserPermissionsG(mods ...qm.QueryMod) authUserUserPermissionQuery {
	return AuthUserUserPermissions(boil.GetDB(), mods...)
}

// AuthUserUserPermissions retrieves all the records using an executor.
func AuthUserUserPermissions(exec boil.Executor, mods ...qm.QueryMod) authUserUserPermissionQuery {
	mods = append(mods, qm.From("`auth_user_user_permissions`"))
	return authUserUserPermissionQuery{NewQuery(exec, mods...)}
}

// FindAuthUserUserPermissionG retrieves a single record by ID.
func FindAuthUserUserPermissionG(id int, selectCols ...string) (*AuthUserUserPermission, error) {
	return FindAuthUserUserPermission(boil.GetDB(), id, selectCols...)
}

// FindAuthUserUserPermissionGP retrieves a single record by ID, and panics on error.
func FindAuthUserUserPermissionGP(id int, selectCols ...string) *AuthUserUserPermission {
	retobj, err := FindAuthUserUserPermission(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAuthUserUserPermission retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAuthUserUserPermission(exec boil.Executor, id int, selectCols ...string) (*AuthUserUserPermission, error) {
	authUserUserPermissionObj := &AuthUserUserPermission{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `auth_user_user_permissions` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(authUserUserPermissionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from auth_user_user_permissions")
	}

	return authUserUserPermissionObj, nil
}

// FindAuthUserUserPermissionP retrieves a single record by ID with an executor, and panics on error.
func FindAuthUserUserPermissionP(exec boil.Executor, id int, selectCols ...string) *AuthUserUserPermission {
	retobj, err := FindAuthUserUserPermission(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AuthUserUserPermission) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *AuthUserUserPermission) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *AuthUserUserPermission) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *AuthUserUserPermission) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no auth_user_user_permissions provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(authUserUserPermissionColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	authUserUserPermissionInsertCacheMut.RLock()
	cache, cached := authUserUserPermissionInsertCache[key]
	authUserUserPermissionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			authUserUserPermissionColumns,
			authUserUserPermissionColumnsWithDefault,
			authUserUserPermissionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, returnColumns)
		if err != nil {
			return err
		}
		cache.query = fmt.Sprintf("INSERT INTO `auth_user_user_permissions` (`%s`) VALUES (%s)", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `auth_user_user_permissions` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, authUserUserPermissionPrimaryKeyColumns))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into auth_user_user_permissions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == authUserUserPermissionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for auth_user_user_permissions")
	}

CacheNoHooks:
	if !cached {
		authUserUserPermissionInsertCacheMut.Lock()
		authUserUserPermissionInsertCache[key] = cache
		authUserUserPermissionInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single AuthUserUserPermission record. See Update for
// whitelist behavior description.
func (o *AuthUserUserPermission) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single AuthUserUserPermission record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *AuthUserUserPermission) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the AuthUserUserPermission, and panics on error.
// See Update for whitelist behavior description.
func (o *AuthUserUserPermission) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the AuthUserUserPermission.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *AuthUserUserPermission) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	authUserUserPermissionUpdateCacheMut.RLock()
	cache, cached := authUserUserPermissionUpdateCache[key]
	authUserUserPermissionUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(authUserUserPermissionColumns, authUserUserPermissionPrimaryKeyColumns, whitelist)
		if len(wl) == 0 {
			return errors.New("models: unable to update auth_user_user_permissions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `auth_user_user_permissions` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, authUserUserPermissionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, append(wl, authUserUserPermissionPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update auth_user_user_permissions row")
	}

	if !cached {
		authUserUserPermissionUpdateCacheMut.Lock()
		authUserUserPermissionUpdateCache[key] = cache
		authUserUserPermissionUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q authUserUserPermissionQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q authUserUserPermissionQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for auth_user_user_permissions")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AuthUserUserPermissionSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o AuthUserUserPermissionSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o AuthUserUserPermissionSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AuthUserUserPermissionSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authUserUserPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"UPDATE `auth_user_user_permissions` SET %s WHERE (`id`) IN (%s)",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(authUserUserPermissionPrimaryKeyColumns), len(colNames)+1, len(authUserUserPermissionPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in authUserUserPermission slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AuthUserUserPermission) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *AuthUserUserPermission) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *AuthUserUserPermission) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AuthUserUserPermission) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no auth_user_user_permissions provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(authUserUserPermissionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	authUserUserPermissionUpsertCacheMut.RLock()
	cache, cached := authUserUserPermissionUpsertCache[key]
	authUserUserPermissionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			authUserUserPermissionColumns,
			authUserUserPermissionColumnsWithDefault,
			authUserUserPermissionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			authUserUserPermissionColumns,
			authUserUserPermissionPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert auth_user_user_permissions, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "auth_user_user_permissions", update, whitelist)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `auth_user_user_permissions` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(authUserUserPermissionType, authUserUserPermissionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for auth_user_user_permissions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == authUserUserPermissionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for auth_user_user_permissions")
	}

CacheNoHooks:
	if !cached {
		authUserUserPermissionUpsertCacheMut.Lock()
		authUserUserPermissionUpsertCache[key] = cache
		authUserUserPermissionUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single AuthUserUserPermission record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AuthUserUserPermission) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single AuthUserUserPermission record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AuthUserUserPermission) DeleteG() error {
	if o == nil {
		return errors.New("models: no AuthUserUserPermission provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single AuthUserUserPermission record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AuthUserUserPermission) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single AuthUserUserPermission record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AuthUserUserPermission) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AuthUserUserPermission provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), authUserUserPermissionPrimaryKeyMapping)
	sql := "DELETE FROM `auth_user_user_permissions` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from auth_user_user_permissions")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q authUserUserPermissionQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q authUserUserPermissionQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no authUserUserPermissionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from auth_user_user_permissions")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o AuthUserUserPermissionSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o AuthUserUserPermissionSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no AuthUserUserPermission slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o AuthUserUserPermissionSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AuthUserUserPermissionSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AuthUserUserPermission slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authUserUserPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"DELETE FROM `auth_user_user_permissions` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, authUserUserPermissionPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(authUserUserPermissionPrimaryKeyColumns), 1, len(authUserUserPermissionPrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from authUserUserPermission slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *AuthUserUserPermission) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *AuthUserUserPermission) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AuthUserUserPermission) ReloadG() error {
	if o == nil {
		return errors.New("models: no AuthUserUserPermission provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AuthUserUserPermission) Reload(exec boil.Executor) error {
	ret, err := FindAuthUserUserPermission(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AuthUserUserPermissionSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AuthUserUserPermissionSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuthUserUserPermissionSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty AuthUserUserPermissionSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuthUserUserPermissionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	authUserUserPermissions := AuthUserUserPermissionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authUserUserPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"SELECT `auth_user_user_permissions`.* FROM `auth_user_user_permissions` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, authUserUserPermissionPrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(authUserUserPermissionPrimaryKeyColumns), 1, len(authUserUserPermissionPrimaryKeyColumns)),
	)

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&authUserUserPermissions)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AuthUserUserPermissionSlice")
	}

	*o = authUserUserPermissions

	return nil
}

// AuthUserUserPermissionExists checks if the AuthUserUserPermission row exists.
func AuthUserUserPermissionExists(exec boil.Executor, id int) (bool, error) {
	var exists bool

	sql := "select exists(select 1 from `auth_user_user_permissions` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if auth_user_user_permissions exists")
	}

	return exists, nil
}

// AuthUserUserPermissionExistsG checks if the AuthUserUserPermission row exists.
func AuthUserUserPermissionExistsG(id int) (bool, error) {
	return AuthUserUserPermissionExists(boil.GetDB(), id)
}

// AuthUserUserPermissionExistsGP checks if the AuthUserUserPermission row exists. Panics on error.
func AuthUserUserPermissionExistsGP(id int) bool {
	e, err := AuthUserUserPermissionExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AuthUserUserPermissionExistsP checks if the AuthUserUserPermission row exists. Panics on error.
func AuthUserUserPermissionExistsP(exec boil.Executor, id int) bool {
	e, err := AuthUserUserPermissionExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
