// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
)

// BraceletRate is an object representing the database table.
type BraceletRate struct {
	ID         int `boil:"id" json:"id" toml:"id" yaml:"id"`
	BraceletID int `boil:"bracelet_id" json:"bracelet_id" toml:"bracelet_id" yaml:"bracelet_id"`
	Rate       int `boil:"rate" json:"rate" toml:"rate" yaml:"rate"`
	UserID     int `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`

	R *braceletRateR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L braceletRateL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// braceletRateR is where relationships are stored.
type braceletRateR struct {
	Bracelet *BraceletBracelet
	User     *AuthUser
}

// braceletRateL is where Load methods for each relationship are stored.
type braceletRateL struct{}

var (
	braceletRateColumns               = []string{"id", "bracelet_id", "rate", "user_id"}
	braceletRateColumnsWithoutDefault = []string{"bracelet_id", "rate", "user_id"}
	braceletRateColumnsWithDefault    = []string{"id"}
	braceletRatePrimaryKeyColumns     = []string{"id"}
)

type (
	// BraceletRateSlice is an alias for a slice of pointers to BraceletRate.
	// This should generally be used opposed to []BraceletRate.
	BraceletRateSlice []*BraceletRate

	braceletRateQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	braceletRateType                 = reflect.TypeOf(&BraceletRate{})
	braceletRateMapping              = queries.MakeStructMapping(braceletRateType)
	braceletRatePrimaryKeyMapping, _ = queries.BindMapping(braceletRateType, braceletRateMapping, braceletRatePrimaryKeyColumns)
	braceletRateInsertCacheMut       sync.RWMutex
	braceletRateInsertCache          = make(map[string]insertCache)
	braceletRateUpdateCacheMut       sync.RWMutex
	braceletRateUpdateCache          = make(map[string]updateCache)
	braceletRateUpsertCacheMut       sync.RWMutex
	braceletRateUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)

// OneP returns a single braceletRate record from the query, and panics on error.
func (q braceletRateQuery) OneP() *BraceletRate {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single braceletRate record from the query.
func (q braceletRateQuery) One() (*BraceletRate, error) {
	o := &BraceletRate{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bracelet_rate")
	}

	return o, nil
}

// AllP returns all BraceletRate records from the query, and panics on error.
func (q braceletRateQuery) AllP() BraceletRateSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all BraceletRate records from the query.
func (q braceletRateQuery) All() (BraceletRateSlice, error) {
	var o BraceletRateSlice

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BraceletRate slice")
	}

	return o, nil
}

// CountP returns the count of all BraceletRate records in the query, and panics on error.
func (q braceletRateQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all BraceletRate records in the query.
func (q braceletRateQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bracelet_rate rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q braceletRateQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q braceletRateQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bracelet_rate exists")
	}

	return count > 0, nil
}

// BraceletG pointed to by the foreign key.
func (o *BraceletRate) BraceletG(mods ...qm.QueryMod) braceletBraceletQuery {
	return o.Bracelet(boil.GetDB(), mods...)
}

// Bracelet pointed to by the foreign key.
func (o *BraceletRate) Bracelet(exec boil.Executor, mods ...qm.QueryMod) braceletBraceletQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.BraceletID),
	}

	queryMods = append(queryMods, mods...)

	query := BraceletBracelets(exec, queryMods...)
	queries.SetFrom(query.Query, "`bracelet_bracelet`")

	return query
}

// UserG pointed to by the foreign key.
func (o *BraceletRate) UserG(mods ...qm.QueryMod) authUserQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *BraceletRate) User(exec boil.Executor, mods ...qm.QueryMod) authUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := AuthUsers(exec, queryMods...)
	queries.SetFrom(query.Query, "`auth_user`")

	return query
}

// LoadBracelet allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (braceletRateL) LoadBracelet(e boil.Executor, singular bool, maybeBraceletRate interface{}) error {
	var slice []*BraceletRate
	var object *BraceletRate

	count := 1
	if singular {
		object = maybeBraceletRate.(*BraceletRate)
	} else {
		slice = *maybeBraceletRate.(*BraceletRateSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &braceletRateR{}
		}
		args[0] = object.BraceletID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &braceletRateR{}
			}
			args[i] = obj.BraceletID
		}
	}

	query := fmt.Sprintf(
		"select * from `bracelet_bracelet` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load BraceletBracelet")
	}
	defer results.Close()

	var resultSlice []*BraceletBracelet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice BraceletBracelet")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Bracelet = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BraceletID == foreign.ID {
				local.R.Bracelet = foreign
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (braceletRateL) LoadUser(e boil.Executor, singular bool, maybeBraceletRate interface{}) error {
	var slice []*BraceletRate
	var object *BraceletRate

	count := 1
	if singular {
		object = maybeBraceletRate.(*BraceletRate)
	} else {
		slice = *maybeBraceletRate.(*BraceletRateSlice)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &braceletRateR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &braceletRateR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from `auth_user` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AuthUser")
	}
	defer results.Close()

	var resultSlice []*AuthUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AuthUser")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// SetBraceletG of the bracelet_rate to the related item.
// Sets o.R.Bracelet to related.
// Adds o to related.R.BraceletBraceletRates.
// Uses the global database handle.
func (o *BraceletRate) SetBraceletG(insert bool, related *BraceletBracelet) error {
	return o.SetBracelet(boil.GetDB(), insert, related)
}

// SetBraceletP of the bracelet_rate to the related item.
// Sets o.R.Bracelet to related.
// Adds o to related.R.BraceletBraceletRates.
// Panics on error.
func (o *BraceletRate) SetBraceletP(exec boil.Executor, insert bool, related *BraceletBracelet) {
	if err := o.SetBracelet(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetBraceletGP of the bracelet_rate to the related item.
// Sets o.R.Bracelet to related.
// Adds o to related.R.BraceletBraceletRates.
// Uses the global database handle and panics on error.
func (o *BraceletRate) SetBraceletGP(insert bool, related *BraceletBracelet) {
	if err := o.SetBracelet(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetBracelet of the bracelet_rate to the related item.
// Sets o.R.Bracelet to related.
// Adds o to related.R.BraceletBraceletRates.
func (o *BraceletRate) SetBracelet(exec boil.Executor, insert bool, related *BraceletBracelet) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `bracelet_rate` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"bracelet_id"}),
		strmangle.WhereClause("`", "`", 0, braceletRatePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BraceletID = related.ID

	if o.R == nil {
		o.R = &braceletRateR{
			Bracelet: related,
		}
	} else {
		o.R.Bracelet = related
	}

	if related.R == nil {
		related.R = &braceletBraceletR{
			BraceletBraceletRates: BraceletRateSlice{o},
		}
	} else {
		related.R.BraceletBraceletRates = append(related.R.BraceletBraceletRates, o)
	}

	return nil
}

// SetUserG of the bracelet_rate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserBraceletRates.
// Uses the global database handle.
func (o *BraceletRate) SetUserG(insert bool, related *AuthUser) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the bracelet_rate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserBraceletRates.
// Panics on error.
func (o *BraceletRate) SetUserP(exec boil.Executor, insert bool, related *AuthUser) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the bracelet_rate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserBraceletRates.
// Uses the global database handle and panics on error.
func (o *BraceletRate) SetUserGP(insert bool, related *AuthUser) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the bracelet_rate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserBraceletRates.
func (o *BraceletRate) SetUser(exec boil.Executor, insert bool, related *AuthUser) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `bracelet_rate` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, braceletRatePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID

	if o.R == nil {
		o.R = &braceletRateR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &authUserR{
			UserBraceletRates: BraceletRateSlice{o},
		}
	} else {
		related.R.UserBraceletRates = append(related.R.UserBraceletRates, o)
	}

	return nil
}

// BraceletRatesG retrieves all records.
func BraceletRatesG(mods ...qm.QueryMod) braceletRateQuery {
	return BraceletRates(boil.GetDB(), mods...)
}

// BraceletRates retrieves all the records using an executor.
func BraceletRates(exec boil.Executor, mods ...qm.QueryMod) braceletRateQuery {
	mods = append(mods, qm.From("`bracelet_rate`"))
	return braceletRateQuery{NewQuery(exec, mods...)}
}

// FindBraceletRateG retrieves a single record by ID.
func FindBraceletRateG(id int, selectCols ...string) (*BraceletRate, error) {
	return FindBraceletRate(boil.GetDB(), id, selectCols...)
}

// FindBraceletRateGP retrieves a single record by ID, and panics on error.
func FindBraceletRateGP(id int, selectCols ...string) *BraceletRate {
	retobj, err := FindBraceletRate(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBraceletRate retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBraceletRate(exec boil.Executor, id int, selectCols ...string) (*BraceletRate, error) {
	braceletRateObj := &BraceletRate{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `bracelet_rate` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(braceletRateObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bracelet_rate")
	}

	return braceletRateObj, nil
}

// FindBraceletRateP retrieves a single record by ID with an executor, and panics on error.
func FindBraceletRateP(exec boil.Executor, id int, selectCols ...string) *BraceletRate {
	retobj, err := FindBraceletRate(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *BraceletRate) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *BraceletRate) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *BraceletRate) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *BraceletRate) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no bracelet_rate provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(braceletRateColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	braceletRateInsertCacheMut.RLock()
	cache, cached := braceletRateInsertCache[key]
	braceletRateInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			braceletRateColumns,
			braceletRateColumnsWithDefault,
			braceletRateColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(braceletRateType, braceletRateMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(braceletRateType, braceletRateMapping, returnColumns)
		if err != nil {
			return err
		}
		cache.query = fmt.Sprintf("INSERT INTO `bracelet_rate` (`%s`) VALUES (%s)", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `bracelet_rate` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, braceletRatePrimaryKeyColumns))
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bracelet_rate")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == braceletRateMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bracelet_rate")
	}

CacheNoHooks:
	if !cached {
		braceletRateInsertCacheMut.Lock()
		braceletRateInsertCache[key] = cache
		braceletRateInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single BraceletRate record. See Update for
// whitelist behavior description.
func (o *BraceletRate) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single BraceletRate record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *BraceletRate) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the BraceletRate, and panics on error.
// See Update for whitelist behavior description.
func (o *BraceletRate) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the BraceletRate.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *BraceletRate) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	key := makeCacheKey(whitelist, nil)
	braceletRateUpdateCacheMut.RLock()
	cache, cached := braceletRateUpdateCache[key]
	braceletRateUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(braceletRateColumns, braceletRatePrimaryKeyColumns, whitelist)
		if len(wl) == 0 {
			return errors.New("models: unable to update bracelet_rate, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `bracelet_rate` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, braceletRatePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(braceletRateType, braceletRateMapping, append(wl, braceletRatePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update bracelet_rate row")
	}

	if !cached {
		braceletRateUpdateCacheMut.Lock()
		braceletRateUpdateCache[key] = cache
		braceletRateUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q braceletRateQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q braceletRateQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for bracelet_rate")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BraceletRateSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BraceletRateSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BraceletRateSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BraceletRateSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), braceletRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"UPDATE `bracelet_rate` SET %s WHERE (`id`) IN (%s)",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(braceletRatePrimaryKeyColumns), len(colNames)+1, len(braceletRatePrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in braceletRate slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *BraceletRate) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *BraceletRate) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *BraceletRate) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *BraceletRate) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no bracelet_rate provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(braceletRateColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	braceletRateUpsertCacheMut.RLock()
	cache, cached := braceletRateUpsertCache[key]
	braceletRateUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		var ret []string
		whitelist, ret = strmangle.InsertColumnSet(
			braceletRateColumns,
			braceletRateColumnsWithDefault,
			braceletRateColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)
		update := strmangle.UpdateColumnSet(
			braceletRateColumns,
			braceletRatePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert bracelet_rate, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "bracelet_rate", update, whitelist)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `bracelet_rate` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(braceletRateType, braceletRateMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(braceletRateType, braceletRateMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for bracelet_rate")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == braceletRateMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bracelet_rate")
	}

CacheNoHooks:
	if !cached {
		braceletRateUpsertCacheMut.Lock()
		braceletRateUpsertCache[key] = cache
		braceletRateUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteP deletes a single BraceletRate record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *BraceletRate) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single BraceletRate record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *BraceletRate) DeleteG() error {
	if o == nil {
		return errors.New("models: no BraceletRate provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single BraceletRate record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *BraceletRate) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single BraceletRate record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BraceletRate) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no BraceletRate provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), braceletRatePrimaryKeyMapping)
	sql := "DELETE FROM `bracelet_rate` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from bracelet_rate")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q braceletRateQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q braceletRateQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no braceletRateQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from bracelet_rate")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BraceletRateSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BraceletRateSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no BraceletRate slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BraceletRateSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BraceletRateSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no BraceletRate slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), braceletRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"DELETE FROM `bracelet_rate` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, braceletRatePrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(o)*len(braceletRatePrimaryKeyColumns), 1, len(braceletRatePrimaryKeyColumns)),
	)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from braceletRate slice")
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *BraceletRate) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *BraceletRate) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *BraceletRate) ReloadG() error {
	if o == nil {
		return errors.New("models: no BraceletRate provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BraceletRate) Reload(exec boil.Executor) error {
	ret, err := FindBraceletRate(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BraceletRateSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BraceletRateSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BraceletRateSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty BraceletRateSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BraceletRateSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	braceletRates := BraceletRateSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), braceletRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf(
		"SELECT `bracelet_rate`.* FROM `bracelet_rate` WHERE (%s) IN (%s)",
		strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, braceletRatePrimaryKeyColumns), ","),
		strmangle.Placeholders(dialect.IndexPlaceholders, len(*o)*len(braceletRatePrimaryKeyColumns), 1, len(braceletRatePrimaryKeyColumns)),
	)

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&braceletRates)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BraceletRateSlice")
	}

	*o = braceletRates

	return nil
}

// BraceletRateExists checks if the BraceletRate row exists.
func BraceletRateExists(exec boil.Executor, id int) (bool, error) {
	var exists bool

	sql := "select exists(select 1 from `bracelet_rate` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bracelet_rate exists")
	}

	return exists, nil
}

// BraceletRateExistsG checks if the BraceletRate row exists.
func BraceletRateExistsG(id int) (bool, error) {
	return BraceletRateExists(boil.GetDB(), id)
}

// BraceletRateExistsGP checks if the BraceletRate row exists. Panics on error.
func BraceletRateExistsGP(id int) bool {
	e, err := BraceletRateExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BraceletRateExistsP checks if the BraceletRate row exists. Panics on error.
func BraceletRateExistsP(exec boil.Executor, id int) bool {
	e, err := BraceletRateExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
